apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-campus-config
  namespace: smart-campus
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"


  DB_HOST:  "smart-campus-postgres.cux84eai66f2.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "smartcampus"
